### ISSUE TITLE
Trackpad Pane in Preferences is blank

### ISSUE THREAD

**Issue by tatthien** [okay/t470#1]
Hi,
Thank for the awesome guide.

My trackpad pane is blank so I cannot config my trackpad in preferences.

What should I do to make it work?

**Comment by okay** [comment]
This has happened to another Reddit user - he said it works great after a few reboots. Let me know if that works.

**Comment by tatthien** [comment]
I have already done it. Restart many times. But the trackpad is still blank.

**Comment by okay** [comment]
@tatthien Is your trackpad PS2 or I2C? Mine breaks occasionally too. I have to restart to get it working again.

**Comment by tatthien** [comment]
My trackpad is PS2

**Comment by okay** [comment]
@tatthien Hmm. Not sure, then. Have you done any other modifications to the repo? I noticed you forked it.

**Comment by tatthien** [comment]
not yet, what modifications I should make? and how to?

**Comment by okay** [comment]
@tatthien Not sure then. Ask r/hackintosh Discord? It works fine for me, and I can't reproduce the issue you're having. Do you have the same model as me? (i5-6300u, 256gb nvme ssd, hd 520 graphics)

**Comment by okay** [comment]
Closing this issue as there has been no response for 4 days.

**Comment by tatthien** [comment]
Sorry for my delay. I've already fixed follow the instruction of RehabMan
https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/wiki/How-to-Install

**Comment by okay** [comment]
@tatthien Can you send me the patch on your fork? I'll merge and credit you.

**Comment by tatthien** [comment]
Hi,
Actually, there's a guy helped me to install MacOS on my machine.
Here is my EFI folder: https://github.com/tatthien/T470-EFI

**Comment by okay** [comment]
@tatthien Oh, sorry that my guide did not help you. I apologize!

I'll merge what's there into this repo and credit you, if that's OK?

**Comment by tatthien** [comment]
It's ok. I'm glad if i can be merged

**Comment by okay** [comment]
@tatthien Will merge and credit once I have time.
