### ISSUE TITLE
Trackpoint Speed

### ISSUE THREAD

**Issue by SourceQuality** [okay/t470#2]
How can we adjust the trackpoint speed?
It's VERY jumpy, and unusable. It seems to only move in steps.

**Comment by okay** [comment]
Hi @SourceQuality!

I'll look into this over the coming days and report back to you.

**Comment by SourceQuality** [comment]
> Hi @SourceQuality!
> 
> I'll look into this over the coming days and report back to you.
> 
> Letting you know your issue has been acknowledged and I will deal with it ASAP.

Thank you! If there is anyway I can help, please let me know.

**Comment by okay** [comment]
@SourceQuality There is a way you could help - I'm on vacation at the moment and my T470 is getting an upgrade while I'm gone, so there's no way for me to test out things. I'll try to post potential patches in the trackpoint-testing branch - if you could test them and let me know if they work that would be great.

Thanks!

**Comment by okay** [comment]
Updating this issue: my T470 is still undergoing its upgrade. Parts are coming from AliExpress so it will be a while still. ETA on when the T470 will be back is about a week ish.
