### ISSUE TITLE
HDMI audio doesn't working

### ISSUE THREAD

**Issue by Thitiphong** [okay/t470#3]
Hi,
My Laptop is Thinkpad X270. All function are working fine except HDMI audio and USB port on left side.

**Comment by okay** [comment]
Hi!
This guide is for a specific model of T470. I don't think it will work on an X270. 

[This](https://github.com/huangyz0918/Hackintosh-Installer-University/tree/master/Clover-Configs/Lenovo/ThinkPad%20X270%20) clover folder seems to work with X270. Try this, perhaps?

Have a great day, and sorry my project couldn't help you.

**Comment by Thitiphong** [comment]
Thank you
